name: ci

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 12 * * *"

jobs:
  container:
    strategy:
      matrix:
        img: [taskd]
        os: [linux]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push GHCR load
        id: docker_build_ghcr_load
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:docker"
          file: "Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args:
            BUILDPLATFORM=${{ matrix.os }}/amd64
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.img }}:latest
